### ISSUE TITLE
Figma Design: -Page- Set-up new User - Forms - Details

### ISSUE THREAD

**Issue by dipanshuhappy** [Buggermenot/KitchHub#3]
Look now let's note down all the info we want from the user 
First Name 
Last Name
Where does he live
Allergics
I know i am missing alot of things ..
@Buggermenot 
@jayeshkumar1951  
please comment down those ones i have missed..(which is alot 😄 )

**Comment by jayeshkumar1951** [comment]
Individual or family(so that we can push recipe posts accordingly)
Favourite foods(should be updatable) 
Cooking experience(a drop down list with funny or food-related option descriptions....eg: Noob - I like being served!  ,  expert(or food nerd or connoisseur) - _some description_ )
 
See, this page shouldn't ask for a lot of info from the user, can't bore them. Simple and quick set-up of account should be our aim.

**Comment by dipanshuhappy** [comment]
Yeah .. there will be few required fields
