### ISSUE TITLE
Figma Dashboard: -Search View- "Star Food", "Recommended Food" ---- Based on area and usage.

### ISSUE THREAD

**Issue by dipanshuhappy** [Buggermenot/KitchHub#4]
This will look like the one in myntra ...

**Comment by jayeshkumar1951** [comment]
1. Top rated posts this week(you can't miss out on these!)  or (fellow foodies rated them yumm-_iest_!)
2. Similar to the above one, maybe one for each month(idk, choose either of these)
3. People in your area also searched/trending dishes in _your location_
4. The usual, _you may also like_
5. If a person has rated a post(upvote/downvote), push them to comment on it....so that there is greater activity n descriptive user feedback....would help us understand what our users feel, n also the contributors......so somewhere on the dashboard, if there are posts that have been rated but not commented on, gently nudge them to leave a comment(idk if this is required, but struck my mind so putting it out here)
